version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(bun)"
    groups:
      ui-dependencies:
        patterns:
          - "*"
    reviewers:
      - "ninepiece2"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(actions)"
    reviewers:
      - "ninepiece2"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(docker)"
    groups:
      docker-images:
        patterns:
          - "*"
    reviewers:
      - "ninepiece2"